# Generated by Django 3.0.1 on 2019-12-29 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=4)),
                ('full_name', models.CharField(max_length=120)),
                ('link', models.URLField()),
                ('auto_import', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('team_num', models.CharField(max_length=5, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=4)),
                ('lat', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
                ('last_year_competing', models.PositiveSmallIntegerField(null=True)),
                ('added_manually', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.Competition')),
            ],
            options={
                'ordering': ['team_num', 'competition'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('lat', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.Competition')),
            ],
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('team_num', 'competition'), name='unique_team'),
        ),
    ]
