# Generated by Django 3.0.1 on 2019-12-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='first_year',
            field=models.IntegerField(default=1992),
        ),
        migrations.AddField(
            model_name='competition',
            name='last_year',
            field=models.IntegerField(default=2019),
        ),
    ]
