# Generated by Django 3.0.1 on 2020-01-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20191230_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='last_year',
            field=models.IntegerField(default=2020),
        ),
    ]
