# Generated by Django 3.0.4 on 2020-03-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20200319_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='nickname',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_num',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='zip_code',
            field=models.TextField(blank=True),
        ),
    ]
