# Generated by Django 3.0.1 on 2019-12-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191226_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammembership',
            options={'ordering': ['team__competition__abbreviation', 'team__team_num']},
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
