# Generated by Django 3.0.1 on 2019-12-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191227_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(related_name='users', through='users.TeamMembership', to='users.Team'),
        ),
    ]
